# Generated by Django 4.0.6 on 2022-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(choices=[('adimplente', 'Adimplente'), ('em_debito', 'Em débito')], default='Adimplente', max_length=10),
        ),
    ]
