# Generated by Django 4.0.6 on 2022-09-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_tema'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('tema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.tema')),
            ],
        ),
    ]
