# Generated by Django 4.1.6 on 2023-06-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_profile_id'),
        ('chamadas', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('pages', '0003_alter_noticia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroturma',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.turma'),
        ),
        migrations.AddField(
            model_name='cadastrotema',
            name='tema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.tema'),
        ),
        migrations.AddField(
            model_name='cadastroprojeto',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.projetomodelo'),
        ),
        migrations.AddField(
            model_name='cadastroprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='cadastronoticia',
            name='noticia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.noticia'),
        ),
        migrations.AddField(
            model_name='cadastrochamada',
            name='chamada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.chamada'),
        ),
    ]
