# Generated by Django 4.0.6 on 2022-09-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7, unique=True)),
                ('deadline_inscricao', models.DateField(null=True, verbose_name='Data limite da inscrição')),
                ('deadline_bibliografia', models.DateField(null=True, verbose_name='Data limite da bibliografia')),
                ('deadline_proposta', models.DateField(null=True, verbose_name='Data limite da proposta')),
                ('deadline_projeto', models.DateField(null=True, verbose_name='Data limite do projeto')),
                ('deadline_chamada', models.DateField(null=True, verbose_name='Data limite da chamada')),
                ('resumo', models.TextField()),
                ('edital', models.FileField(upload_to='pdf/%Y/%m/%d/')),
                ('aviso', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('equipe', models.CharField(max_length=100)),
                ('membro_1', models.CharField(blank=True, max_length=100, null=True)),
                ('membro_2', models.CharField(blank=True, max_length=100, null=True)),
                ('membro_3', models.CharField(blank=True, max_length=100, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.chamada')),
                ('lider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.tema')),
            ],
        ),
    ]
