# Generated by Django 4.0.6 on 2022-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7, unique=True)),
                ('deadline_inscricao', models.DateField(null=True, verbose_name='Data limite da inscrição')),
                ('deadline_bibliografia', models.DateField(null=True, verbose_name='Data limite da bibliografia')),
                ('deadline_proposta', models.DateField(null=True, verbose_name='Data limite da proposta')),
                ('deadline_projeto', models.DateField(null=True, verbose_name='Data limite do projeto')),
                ('deadline_chamada', models.DateField(null=True, verbose_name='Data limite da chamada')),
                ('resumo', models.TextField()),
                ('edital', models.FileField(upload_to='')),
                ('aviso', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
