# Generated by Django 4.0.6 on 2022-09-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7, unique=True)),
                ('deadline_inscricao', models.DateField(null=True, verbose_name='Data limite da inscrição')),
                ('deadline_bibliografia', models.DateField(null=True, verbose_name='Data limite da bibliografia')),
                ('deadline_proposta', models.DateField(null=True, verbose_name='Data limite da proposta')),
                ('deadline_projeto', models.DateField(null=True, verbose_name='Data limite do projeto')),
                ('deadline_chamada', models.DateField(null=True, verbose_name='Data limite da chamada')),
                ('resumo', models.TextField()),
                ('edital', models.FileField(upload_to='pdf/%Y/%m/%d/')),
                ('aviso', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('penalidade', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('divulgacao', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('nota', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('equipe', models.CharField(max_length=100)),
                ('membro_1', models.CharField(blank=True, max_length=100, null=True)),
                ('membro_2', models.CharField(blank=True, max_length=100, null=True)),
                ('membro_3', models.CharField(blank=True, max_length=100, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamadas.chamada')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('bibliografia_total', models.IntegerField(blank=True, default=10)),
                ('introducao_titulo_1', models.CharField(default='Qual é o significado?', max_length=100, verbose_name='1. Introdução (parâmetro): Título')),
                ('introducao_peso_1', models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso')),
                ('introducao_titulo_2', models.CharField(default='Qual é a utilidade?', max_length=100, verbose_name='2. Introdução (parâmetro): Título')),
                ('introducao_peso_2', models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='1. Introdução (parâmetro): Peso')),
                ('introducao_titulo_3', models.CharField(default='Quais as vantagens e desvantagens?', max_length=100, verbose_name='3. Introdução (parâmetro): Título')),
                ('introducao_peso_3', models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso')),
                ('introducao_titulo_4', models.CharField(default='O que já foi feito sobre o assunto?', max_length=100, verbose_name='4. Introdução (parâmetro): Título')),
                ('introducao_peso_4', models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso')),
                ('introducao_titulo_5', models.CharField(default='As referências bibliográficas foram citadas corretamente?', max_length=100, verbose_name='5. Introdução (parâmetro): Título')),
                ('introducao_peso_5', models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso')),
                ('introducao_peso', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Introdução: Peso')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('teoria_total', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('teoria_qde', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.inscricao')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.projetomodelo')),
            ],
        ),
        migrations.CreateModel(
            name='Introducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('introducao_nota_1', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('introducao_nota_2', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('introducao_nota_3', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('introducao_nota_4', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('introducao_nota_5', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('nota_introducao', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamadas.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamadas.tema'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='projetomodelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.projetomodelo'),
        ),
    ]
