# Generated by Django 4.0.6 on 2022-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetomodelo',
            name='bibliografia_peso',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6, verbose_name='Bibliografia: Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='proposta_peso',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6, verbose_name='Proposta: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6, verbose_name='Apresentação: Peso'),
        ),
    ]
