# Generated by Django 4.0.6 on 2022-09-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='introducao_nota_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
