# Generated by Django 4.0.6 on 2022-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='divulgacao',
            new_name='divulgacao_nota',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='penalidade',
            new_name='penalidade_nota',
        ),
        migrations.AddField(
            model_name='extra',
            name='divulgacao_consideracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='penalidade_consideracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='consideracoes',
            field=models.CharField(blank=True, default='A proposta atende os objetivos da chamada.', max_length=255, null=True),
        ),
    ]
