# Generated by Django 4.1.6 on 2023-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_titulo_2',
            field=models.CharField(default='Nenhum critério atribuido', max_length=100, verbose_name='2. Resultado (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_titulo_3',
            field=models.CharField(default='Nenhum critério atribuido', max_length=100, verbose_name='3. Resultado (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_titulo_4',
            field=models.CharField(default='Nenhum critério atribuido', max_length=100, verbose_name='4. Resultado (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_titulo_5',
            field=models.CharField(default='Nenhum critério atribuido', max_length=100, verbose_name='5. Resultado (parâmetro): Título'),
        ),
    ]
