# Generated by Django 4.1.6 on 2023-06-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='apresentacao',
        ),
    ]
