# Generated by Django 4.0.6 on 2022-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
