# Generated by Django 4.0.6 on 2022-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='arquivo',
            field=models.FileField(null=True, upload_to='pdf/%Y/%m/%d/'),
        ),
    ]
