# Generated by Django 4.0.6 on 2022-09-19 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_projeto_introducao_nota_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='projetomodelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.projetomodelo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.projetomodelo'),
        ),
    ]
