# Generated by Django 4.0.6 on 2022-09-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_remove_metodologia_teoria_qde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teoria',
            name='teoria_consideracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
