# Generated by Django 4.1.6 on 2023-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_alter_bibliografia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliografia',
            name='arquivo',
            field=models.FileField(default='pdf/modelo-vazio.pdf', null=True, upload_to='pdf/%Y/%m/%d/'),
        ),
    ]
