# Generated by Django 4.0.6 on 2022-09-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_alter_projeto_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducao',
            name='introducao_consideracao_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introducao',
            name='introducao_consideracao_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introducao',
            name='introducao_consideracao_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introducao',
            name='introducao_consideracao_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='introducao',
            name='introducao_consideracao_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=6, verbose_name='1. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
    ]
