# Generated by Django 4.0.6 on 2022-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_rename_divulgacao_extra_divulgacao_nota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nota',
            new_name='nota_projeto',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
