# Generated by Django 4.1.6 on 2023-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_alter_projetomodelo_resultado_titulo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso',
            field=models.DecimalField(decimal_places=3, default=30, max_digits=6, verbose_name='Resultado: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.01, max_digits=6, verbose_name='1. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='teoria_peso',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=6, verbose_name='Teoria: Peso'),
        ),
    ]
