# Generated by Django 4.0.6 on 2022-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0002_alter_chamada_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='edital',
            field=models.FileField(upload_to='pdf/%Y/%m/%d/'),
        ),
    ]
