# Generated by Django 4.0.6 on 2022-09-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_chamada_projetomodelo_alter_projeto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='projetomodelo',
            field=models.ForeignKey(default='Padrão', null=True, on_delete=django.db.models.deletion.PROTECT, to='chamadas.projetomodelo'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='nome',
            field=models.CharField(default='Padrão', max_length=100),
        ),
    ]
