# Generated by Django 4.1.6 on 2023-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_auto_20221017_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bibliografia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_consideracao_1',
            field=models.CharField(blank=True, default='A equipe não enviou o relatório do trabalho', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_consideracao_2',
            field=models.CharField(blank=True, default='A equipe não enviou o relatório do trabalho', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_consideracao_3',
            field=models.CharField(blank=True, default='A equipe não enviou o relatório do trabalho', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_consideracao_4',
            field=models.CharField(blank=True, default='A equipe não enviou o relatório do trabalho', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_consideracao_5',
            field=models.CharField(blank=True, default='A equipe não enviou o relatório do trabalho', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metodologia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
