# Generated by Django 4.1.6 on 2023-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_alter_bibliografia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliografia',
            name='arquivo',
            field=models.FileField(null='True', upload_to='pdf/%Y/%m/%d/'),
        ),
    ]
