# Generated by Django 4.0.6 on 2022-09-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_teoria_teoria_consideracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teoria',
            name='teoria_qde',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='teoria',
            name='teoria_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
