# Generated by Django 4.0.6 on 2022-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0003_rename_nota_projeto_nota_projeto_inscricao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='proposta_status',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3),
        ),
    ]
