# Generated by Django 4.1.6 on 2023-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_alter_apresentacao_id_alter_bibliografia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_prop_1',
            field=models.CharField(choices=[('Direta', 'direta'), ('Inversa', 'inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_prop_2',
            field=models.CharField(choices=[('Direta', 'direta'), ('Inversa', 'inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_prop_3',
            field=models.CharField(choices=[('Direta', 'direta'), ('Inversa', 'inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_prop_4',
            field=models.CharField(choices=[('Direta', 'direta'), ('Inversa', 'inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_prop_5',
            field=models.CharField(choices=[('direta', 'Direta'), ('inversa', 'Inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
    ]
