# Generated by Django 4.0.6 on 2022-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_proposta_proposta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nota_projeto',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6, null=True),
        ),
    ]
