# Generated by Django 4.0.6 on 2022-09-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_alter_teoria_teoria_qde_alter_teoria_teoria_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teoria',
            name='teoria_total',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
