# Generated by Django 4.1.6 on 2023-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_alter_bibliografia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_status',
            field=models.CharField(choices=[('comum', 'Comum'), ('em destaque', 'Em destaque')], default='comum', max_length=11),
        ),
    ]
