# Generated by Django 4.0.6 on 2022-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0004_alter_chamada_projetomodelo_alter_projetomodelo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
