# Generated by Django 4.0.6 on 2022-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0005_alter_teoria_teoria_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(null=True),
        ),
    ]
