# Generated by Django 4.1.6 on 2023-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0005_inscricao_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='inscricao_status',
            field=models.CharField(choices=[('comum', 'Comum'), ('destaque', 'Em destaque')], default='comum', max_length=11),
        ),
    ]
