# Generated by Django 4.0.6 on 2022-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0006_chamada_orcamento_projeto_imagem_projeto_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetomodelo',
            name='apresentacao_peso',
            field=models.DecimalField(decimal_places=3, default=12.5, max_digits=6, verbose_name='apresentacao: Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='metodologia_peso',
            field=models.DecimalField(decimal_places=3, default=12.5, max_digits=6, verbose_name='Metodologia: Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso',
            field=models.DecimalField(decimal_places=3, default=31.25, max_digits=6, verbose_name='resultado: Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='teoria_peso',
            field=models.DecimalField(decimal_places=3, default=31.25, max_digits=6, verbose_name='Teoria: Peso'),
        ),
    ]
