# Generated by Django 4.0.6 on 2022-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0006_alter_projeto_nota_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6, verbose_name='Introdução: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6, verbose_name='Metodologia: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Metodologia (parâmetro): Peso'),
        ),
    ]
