# Generated by Django 4.0.6 on 2022-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0007_alter_projetomodelo_introducao_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='financeiro_status',
            field=models.CharField(choices=[('adimplente', 'Adimplente'), ('em_debito', 'Em débito')], default='Adimplente', max_length=10),
        ),
    ]
