# Generated by Django 4.0.6 on 2022-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0008_alter_projetomodelo_apresentacao_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teoria',
            name='teoria_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
