# Generated by Django 4.1.6 on 2023-05-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0008_alter_inscricao_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_prop_1',
            field=models.CharField(choices=[('Direta', 'direta'), ('Inversa', 'inversa')], default='direta', max_length=7, verbose_name='1. Resultado (parâmetro): Proporção'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_prop_2',
            field=models.CharField(choices=[('direta', 'Direta'), ('inversa', 'Inversa')], default='direta', max_length=7, verbose_name='2. Resultado (parâmetro): Proporção'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_prop_3',
            field=models.CharField(choices=[('direta', 'Direta'), ('inversa', 'Inversa')], default='direta', max_length=7, verbose_name='3. Resultado (parâmetro): Proporção'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_prop_4',
            field=models.CharField(choices=[('direta', 'Direta'), ('inversa', 'Inversa')], default='direta', max_length=7, verbose_name='4. Resultado (parâmetro): Proporção'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_prop_5',
            field=models.CharField(choices=[('direta', 'Direta'), ('inversa', 'Inversa')], default='direta', max_length=7, verbose_name='5. Resultado (parâmetro): Proporção'),
        ),
    ]
