# Generated by Django 4.1.6 on 2023-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0009_alter_projetomodelo_resultado_prop_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Apresentação (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Apresentação (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='3. Apresentação (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='4. Apresentação (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='5. Apresentação (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='3. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='4. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='5. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=6, verbose_name='1. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='2. Resultado (parâmetro): Peso'),
        ),
    ]
