# Generated by Django 4.0.6 on 2022-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0009_alter_teoria_teoria_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducao',
            name='introducao_nota_1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_nota_2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_nota_3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_nota_4',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='introducao_nota_5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='introducao',
            name='nota_introducao',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
