# Generated by Django 4.0.6 on 2022-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0010_alter_introducao_introducao_nota_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='apresentacao: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Introdução: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='1. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.02, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Metodologia: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso',
            field=models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='resultado: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='teoria_peso',
            field=models.DecimalField(decimal_places=3, default=0.25, max_digits=6, verbose_name='Teoria: Peso'),
        ),
    ]
