# Generated by Django 4.0.6 on 2022-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0011_alter_projetomodelo_apresentacao_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=6, verbose_name='resultado: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='teoria_peso',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=6, verbose_name='Teoria: Peso'),
        ),
    ]
