# Generated by Django 4.0.6 on 2022-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0013_metodologia_metodologia_consideracao_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='1. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='1. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
    ]
