# Generated by Django 4.0.6 on 2022-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0014_alter_projetomodelo_introducao_peso_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='teoria_qde',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='teoria_total',
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_input_1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_input_2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_input_3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_input_4',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_input_5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
