# Generated by Django 4.0.6 on 2022-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0015_remove_resultado_teoria_qde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AddField(
            model_name='projetomodelo',
            name='resultado_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Introdução (parâmetro): Peso'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_nota_1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_nota_2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_nota_3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_nota_4',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_nota_5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
