# Generated by Django 4.0.6 on 2022-09-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0016_projetomodelo_resultado_peso_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='resultado_fback_1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_fback_2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_fback_3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_fback_4',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_fback_5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
