# Generated by Django 4.0.6 on 2022-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0018_alter_resultado_resultado_fback_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='resultado_fback_1',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_fback_2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_fback_3',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_fback_4',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado_fback_5',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, null=True),
        ),
    ]
