# Generated by Django 4.0.6 on 2022-09-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0019_alter_resultado_resultado_fback_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='apresentacao_peso',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Apresentacao: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='introducao_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Introdução (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='2. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='3. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='4. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.002, max_digits=6, verbose_name='5. Metodologia (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_titulo_1',
            field=models.CharField(default='Como o equipamento ou experimento poderia ser reproduzido?', max_length=100, verbose_name='1. Metodologia (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_titulo_2',
            field=models.CharField(default='A lista de materiais e/ou softwares necessários foi fornecido?', max_length=100, verbose_name='2. Metodologia (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_titulo_3',
            field=models.CharField(default='O custo financeiro total ou detalhado por item foi fornecido?', max_length=100, verbose_name='3. Metodologia (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_titulo_4',
            field=models.CharField(default='O procedimento para a perfeita utilização foi apresentado de maneira clara e objetiva?', max_length=100, verbose_name='4. Metodologia (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='metodologia_titulo_5',
            field=models.CharField(default='Uma imagem clara do dispositivo, ou no caso de software o link para o seu repositório foi fornecido?', max_length=100, verbose_name='5. Metodologia (parâmetro): Título'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=6, verbose_name='Resultado: Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_1',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='1. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_2',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='2. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='3. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='4. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.005, max_digits=6, verbose_name='5. Resultado (parâmetro): Peso'),
        ),
    ]
