# Generated by Django 4.0.6 on 2022-09-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamadas', '0020_alter_projetomodelo_apresentacao_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_3',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='3. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_4',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='4. Resultado (parâmetro): Peso'),
        ),
        migrations.AlterField(
            model_name='projetomodelo',
            name='resultado_peso_5',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='5. Resultado (parâmetro): Peso'),
        ),
    ]
