@startuml PROGRESSUS
package users{
    entity User{
        id: integer
        username: varchar
        email: varchar
    }
    entity Profile{
        id: integer
        nome_completo: varchar
        turma: varchar
        usuario: varchar
        fk_id_usuario: integer
    }
    Profile "(1,1)" -- "(1,1)" User
}
package chamadas{
    entity Chamada{
        id: integer
        fk_id_tema: integer
        fk_id_inscricao: integer
        nome = varchar
        deadline_inscricao: date
        deadline_bibliografia: date
        deadline_proposta: date
        deadline_projeto: date
        deadline_chamada: date
        resumo: varchar
        edital: file
        aviso = varchar
    }
    entity Tema{
        id: integer
        titulo: varchar
        descricao: varchar
        requisitos: varchar
    }
    entity Inscricao{
        id: integer
        fk_id_lider: integer
        ranking: integer
        nota_projeto: float
        membro_1: varchar
        membro_2: varchar
        membro_3: varchar
        bibliografia: float
        introducao: float
        setNota_projeto()
        setRanking()
    }
    Tema "(N,N)" -- "(N,N)" Inscricao
    Chamada "(1,1)" -- "(1,N)" Inscricao
    entity Extra{
        id: integer
    }
    Inscricao "(1,1)" - "(1,1)" Extra
    entity Projeto{
        id: integer
    }
    Inscricao "(1,1)" -- "(1,1)" Projeto
    entity Bibliografia{
        id: integer
    }
    Projeto "(1,1)" -- "(1,1)" Bibliografia
    entity Introducao{
        id: integer
    }
    Projeto "(1,1)" -- "(1,1)" Introducao
    entity Teoria{
        id: integer
    }
    Projeto "(1,1)" -- "(1,1)" Teoria
    entity Metodologia{
        id: integer
    }
    Projeto "(1,1)" -- "(1,1)" Metodologia
    entity Resultado{
        id: integer
    }
    Projeto "(1,1)" -- "(1,1)" Resultado
}
package pages{
    entity Noticia{
        id: integer
        titulo: varchar
        texto: varchar
        link: url
        imagem: image        
    }
}
package cadastros{
    entity CadastroProfile{
        id: integer
        created: date
        updated: date
        fk_id_profile: integer
    }
    CadastroProfile "(1,1)" -- "(1,1)" Profile
    entity CadastroChamada{
        id: integer
        created: date
        updated: date
        fk_id_chamada: integer
    }
    CadastroChamada "(1,1)" -- "(1,1)" Chamada
    entity CadastroTema{
        id: integer
        created: date
        updated: date
        fk_id_tema: integer
    }
    CadastroTema "(1,1)" -- "(1,1)" Tema
    entity CadastroNoticia{
        id: integer
        created: date
        updated: date
        fk_id_noticia: integer
    }
    CadastroNoticia "(1,1)" -- "(1,1)" Noticia
}
@enduml