@startuml PROGRESSUS
package users{
    entity User{
        id: integer
        username: varchar
        email: varchar
    }
    entity Profile{
        id: integer
        nome_completo: varchar
        turma: varchar
        usuario: varchar
        fk_id_usuario: integer
    }
    Profile "(1,1)" -- "(1,1)" User
}
package chamadas{
    entity Chamada{
        id: integer
        fk_id_projetomodelo: integer
        nome: varchar
        deadline_inscricao: date
        deadline_bibliografia: date
        deadline_proposta: date
        deadline_projeto: date
        deadline_chamada: date
        resumo: varchar
        edital: file
        aviso: varchar
        get_status()
        get_bibliografia()
        get_proposta()
        get_projeto()
    }
    entity Tema{
        id: integer
        titulo: varchar
        descricao: varchar
        requisitos: varchar
    }
    entity Turma{
        nome: varchar
        total_alunos: integer
    }
    entity Inscricao{
        id: integer
        fk_id_lider: integer
        fk_id_chamada: integer
        fk_id_tema: integer
        fk_id_turma: integer
        created: date
        ranking: integer
        equipe: varchar
        membro_1: varchar
        membro_2: varchar
        membro_3: varchar
        ranking: integer
    }
    entity ProjetoModelo{
        id: integer
        created: date
        updated: date
        bibliografia_total: integer
        introducao_titulo_1: varchar
        introducao_peso_1: float
        introducao_titulo_2: varchar
        introducao_peso_2: float
        introducao_titulo_3: varchar
        introducao_peso_3: float
        introducao_titulo_4: varchar
        introducao_peso_4: float
        introducao_titulo_5: varchar
        introducao_peso_5: float
        metodologia_titulo_1: varchar
        metodologia_peso_1: float
        metodologia_titulo_2: varchar
        metodologia_peso_2: float
        metodologia_titulo_3: varchar
        metodologia_peso_3: float
        metodologia_titulo_4: varchar
        metodologia_peso_4: float
        metodologia_titulo_5: varchar
        metodologia_peso_5: float
        resultado_titulo_1: varchar
        resultado_peso_1: float
        resultado_titulo_2: varchar
        resultado_peso_2: float
        resultado_titulo_3: varchar
        resultado_peso_3: float
        resultado_titulo_4: varchar
        resultado_peso_4: float
        resultado_titulo_5: varchar
        resultado_peso_5: float
        resultado_prop_1: varchar
        resultado_prop_2: varchar
        resultado_prop_3: varchar
        resultado_prop_4: varchar
        resultado_prop_5: varchar
        apresentacao_titulo_1: varchar
        apresentacao_peso_1: float
        apresentacao_titulo_2: varchar
        apresentacao_peso_2: float
        apresentacao_titulo_3: varchar
        apresentacao_peso_3: float
        apresentacao_titulo_4: varchar
        apresentacao_peso_4: float
        apresentacao_titulo_5: varchar
        apresentacao_peso_5: float
        introducao_peso: float
        teoria_peso: float
        metodologia_peso: float
        resultado_peso: float
        apresentacao_peso: float
        bibliografia_peso: float
        proposta_peso: float
    }
    entity Projeto{
        id: integer
        fk_id_inscricao: integer
        fk_id_modelo: integer
        created: date
        updated: date
        titulo: varchar
        nota_projeto: float
        arquivo: varchar
        resumo: varchar
        resumo: varchar
        imagem: varchar
        setNotaProjeto()
    }
    entity Introducao{
        id: integer
        fk_id_projeto: integer
        created: date
        updated: date
        introducao_nota_1: float
        introducao_nota_2: float
        introducao_nota_3: float
        introducao_nota_4: float
        introducao_nota_5: float
        introducao_consideracao_1: varchar
        introducao_consideracao_2: varchar
        introducao_consideracao_3: varchar
        introducao_consideracao_4: varchar
        introducao_consideracao_5: varchar
        nota_introducao: float
        setNotaIntroducao()

    }
    entity Teoria{
        id: integer
        fk_id_projeto: integer
        created: date
        updated: date
        teoria_total: integer
        teoria_qde: integer
        teoria_consideracao: varchar
        nota_teoria: float
        setNotaTeoria()
    }
    entity Metodologia{
        id: integer
        fk_id_projeto: integer
        created: date
        updated: date
        metodologia_nota_1: float
        metodologia_nota_2: float
        metodologia_nota_3: float
        metodologia_nota_4: float
        metodologia_nota_5: float
        metodologia_consideracao_1: varchar
        metodologia_consideracao_2: varchar
        metodologia_consideracao_3: varchar
        metodologia_consideracao_4: varchar
        metodologia_consideracao_5: varchar
        nota_metodologia: float
        setNotaMetodologia()
    }
    entity Resultado{
        id: integer       
        created: date
        updated: date
        fk_id_projeto: integer
        resultado_input_1: float
        resultado_input_2: float
        resultado_input_3: float
        resultado_input_4: float
        resultado_input_5: float
        resultado_fback_1: float
        resultado_fback_2: float
        resultado_fback_3: float
        resultado_fback_4: float
        resultado_fback_5: float
        resultado_nota_1: float
        resultado_nota_2: float
        resultado_nota_3: float
        resultado_nota_4: float
        resultado_nota_5: float
        resultado_consideracao_1: varchar
        resultado_consideracao_2: varchar
        resultado_consideracao_3: varchar
        resultado_consideracao_4: varchar
        resultado_consideracao_5: varchar
        nota_resultado: float
        setNotaResultado()
    }
    entity Apresentacao{
        id: integer
        created: date
        updated: date
        fk_id_inscricao: integer
        fk_id_modelo: integer
        apresentacao_nota_1: float
        apresentacao_nota_2: float
        apresentacao_nota_3: float
        apresentacao_nota_4: float
        apresentacao_nota_5: float
        apresentacao_consideracao_1: varchar
        apresentacao_consideracao_2: varchar
        apresentacao_consideracao_3: varchar
        apresentacao_consideracao_4: varchar
        apresentacao_consideracao_5: varchar
        nota_apresentacao: float
        setNotaApresentacao()
    }
    entity Extra{
        id: integer
        created: date
        updated: date
        fk_id_inscricao: integer
        nota_extra: float
        penalidade_nota: float
        divulgacao_nota: float
        penalidade_consideracao: varchar
        divulgacao_consideracao: varchar
        setNotaExtra()
    }
    entity Bibliografia{
        id: integer
        fk_id_inscricao: integer
        fk_id_modelo: integer
        created: date
        updated: date
        arquivo: varchar
        bibliografia_qde: integer
        consideracoes: varchar
        nota_bibliografia: float
        setNotaBibliografia()
    }
    entity Proposta{
        id: integer
        created: date
        updated: date
        fk_id_inscricao: integer
        fk_id_modelo: integer
        consideracoes: varchar
        nota_proposta: float
        conteudo: varchar
        proposta_status: varchar        
        setNotaProposta()
    }
    entity Financeiro{
        id: integer
        created: date
        updated: date
        fk_id_inscricao: integer
        comprovante_1: varchar
        comprovante_2: varchar
        comprovante_3: varchar
        consideracoes: varchar
        financeiro_status: varchar
    }
    ProjetoModelo "(1,1)" - "(1,N)" Chamada
    Inscricao "(1,1)" - "(1,1)" Projeto
    Inscricao "(1,1)" - "(1,1)" Profile
    ProjetoModelo "(1,1)" - "(1,1)" Projeto
    Projeto "(1,1)" -- "(1,1)" Introducao
    Projeto "(1,1)" -- "(1,1)" Teoria
    Projeto "(1,1)" -- "(1,1)" Metodologia
    Projeto "(1,1)" -- "(1,1)" Resultado
    Extra "(1,1)" -- "(1,1)" Inscricao
    Bibliografia "(1,N)" -- "(1,1)" ProjetoModelo
    Bibliografia "(1,1)" -- "(1,1)" Inscricao
    Proposta "(1,N)" -- "(1,1)" ProjetoModelo
    Proposta "(1,1)" -- "(1,1)" Inscricao
    Turma "(1,1)" -- "(1,N)" Inscricao
    Tema "(1,1)" -- "(1,N)" Inscricao
    Chamada "(1,1)" -- "(1,N)" Inscricao
    Financeiro "(1,1)" -- "(1,1)" Inscricao
    Apresentacao "(1,1)" -- "(1,1)" Inscricao
    Apresentacao "(1,N)" -- "(1,1)" ProjetoModelo
}
package pages{
    entity Noticia{
        id: integer
        titulo: varchar
        texto: varchar
        link: url
        imagem: image        
    }
}
package cadastros{
    entity CadastroProfile{
        id: integer
        created: date
        updated: date
        fk_id_profile: integer
    }
    CadastroProfile "(1,1)" --- "(1,1)" Profile
    entity CadastroChamada{
        id: integer
        created: date
        updated: date
        fk_id_chamada: integer
    }
    CadastroChamada "(1,1)" -- "(1,1)" Chamada
    entity CadastroTema{
        id: integer
        created: date
        updated: date
        fk_id_tema: integer
    }
    CadastroTema "(1,1)" -- "(1,1)" Tema
    entity CadastroNoticia{
        id: integer
        created: date
        updated: date
        fk_id_noticia: integer
    }
    CadastroNoticia "(1,1)" --- "(1,1)" Noticia
}
@enduml
