@startuml PROGRESSUS
package users{
    entity User{
        id: integer
        username: varchar(50)
        email: varchar(50)
    }
    entity Profile{
        id: integer
        nome_completo: varchar(50)
        turma: varchar(4)
        usuario: varchar(50)
        fk_id_usuario: integer
    }
    Profile "(1,1)" -- "(1,1)" User
}
package chamadas{
    entity Chamada{
        id: integer
        nome = varchar(7)
        deadline_inscricao: date
        deadline_bibliografia: date
        deadline_proposta: date
        deadline_projeto: date
        deadline_chamada: date
        resumo: varchar()
        edital: file
        aviso = varchar()
    }
    entity Tema{
        id: integer
        titulo: varchar(255)
        descricao: varchar
        requisitos: varchar
    }
    entity Inscricao{
        id: integer
        fk_id_chamada: integer
        fk_id_tema: integer
        fk_id_profile: integer
        lider: varchar
        membro_1: varchar
        membro_2: varchar
        membro_3: varchar
        bibliografia: float
        introducao: float
    }
    Tema "(1,N)" -- "(1,1)" Inscricao
    Chamada "(1,1)" -- "(1,N)" Inscricao
}
package cadastros{
    entity CadastroProfile{
        id: integer
        created: date
        updated: date
        fk_id_profile: integer
    }
    CadastroProfile "(1,1)" -- "(1,1)" Profile
    entity CadastroChamada{
        id: integer
        created: date
        updated: date
        fk_id_chamada: integer
    }
    CadastroChamada "(1,1)" -- "(1,1)" Chamada
    entity CadastroTema{
        id: integer
        created: date
        updated: date
        fk_id_tema: integer
    }
    CadastroTema "(1,1)" -- "(1,1)" Tema
}
@enduml